defaults:
    - _self_
    - price_model: gbm
    - agent: ewmac
    - plotting: standard

# Training
train: true # Whether to optimize the agents parameters
seed: 42

# Environment configuration
starting_cash: 100000
window: 160 # Number of days to look back
start_time: 161
start_backtest: 1000 # Time to start backtest from
n_steps: 2000 # ~ 8 years
dt: 0.004 # ~ 1/252

# Logging configuration
use_wandb: false
verbose: false
experiment_name: simple_rules
