defaults:
    - _self_
    - price_model: multi_gbm
    - agent: ewmac
    - plotting: standard

# Training
train_agents: false
optimize_portfolio: true
seed: 42

# Environment configuration
starting_cash: 100000
window: 100
start_time: 150
start_backtest: 1000
n_instruments: 3
n_steps: 2000 # ~ 8 years
dt: 0.004 # ~ 1/252

# Portfolio optimization
risk_free_rate: 0.0
target_vol: 0.15

# Logging configuration
use_wandb: false
verbose: false
experiment_name: portfolio_optimization
