defaults:
    - _self_
    - price_model: gbm
    - plotting: standard

# Training parameters
seed: 42
device: cuda
epochs: 1000
batch_size: 256
lr: 1e-3
val_split: 0.1
shuffle_dataloader: false

# Environment configuration
n_steps: 2000 # ~ 8 years
dt: 0.004 # ~ 1/252 daily
use_synthetic_data: false # Use synthetic data 
time_series: USDJPY

# Model configuration
member_cfg:
    _target_: deeptrade.models.MLPForecastModel
    in_size: 70
    hid_size: 256
    out_size: 20
    num_layers: 3
    device: ${device}
ensemble_size: 15
propagation_method: expectation # Not implemented on forecast model

# Logging configuration
use_wandb: false
verbose: false
experiment_name: single_forecast
